spring.application.name=edutrack-backend
server.port=8080

# Neon PostgreSQL Database configuration
spring.datasource.url=${URL}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=${USERNAME}
spring.datasource.password=${PASSWORD}

# JPA / Hibernate configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
